fastlane_require 'dotenv'

before_all do
  Dotenv.overload('.env')
end

platform :android do
  desc "RN Production App"
  branch = git_branch
  commit = last_git_commit
  lane :distribute do
    gradle(task: 'clean assembleRelease', project_dir: './android', print_command: false, properties: {
      "ANDROID_UPLOAD_STORE_FILE" => ENV["ANDROID_UPLOAD_STORE_FILE"],
      "ANDROID_UPLOAD_STORE_PASSWORD" => ENV["ANDROID_UPLOAD_STORE_PASSWORD"],
      "ANDROID_UPLOAD_KEY_ALIAS" => ENV["ANDROID_UPLOAD_KEY_ALIAS"],
      "ANDROID_UPLOAD_KEY_PASSWORD" => ENV["ANDROID_UPLOAD_KEY_PASSWORD"]
    })

    firebase_app_distribution(
      app: "1:550242178970:android:5668a8a010e37d0c590c23",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      release_notes: "Built from BRANCH: #{branch} COMMIT: #{commit}",
    )
  end
end
