fastlane_require 'dotenv'

before_all do
  Dotenv.overload('.env')
end

platform :android do  
  desc "Build apk"
    lane :build_package do
        gradle(
            task: 'assemble',
            build_type: 'Release',
            properties: {
                "android.injected.signing.store.file" => Dir.pwd + "/release-key.keystore",
                "android.injected.signing.store.password" => ENV["ANDROID_UPLOAD_STORE_PASSWORD"],
                "android.injected.signing.key.alias" => ENV["ANDROID_UPLOAD_KEY_ALIAS"],
                "android.injected.signing.key.password" => ENV["ANDROID_UPLOAD_KEY_PASSWORD"]
            }
        )
    end
  
  desc "Upload aab to Firebase App Distribution"
    lane :upload_to_firebase do
        branch = git_branch
        commit = last_git_commit
        firebase_app_distribution(
        app: "1:550242178970:android:5668a8a010e37d0c590c23",
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        release_notes: "Built from BRANCH: #{branch} COMMIT: #{commit}",
      )
    end
  
  desc "Delete the build directory, generated apk or aab"
    lane :clean_up do
        gradle(
            task: "clean",
            project_dir: "android",
        )
    end

  desc "Build, ulpoad aab to FB, delete build"
    lane :all_lanes do 
      build_package
      upload_to_firebase
      clean_up
    end
end
